### PR TITLE
as=html => as=document (closes #79)

### LINKED ISSUE #79: [Editorial] Update resource fetch example.
Example 7 at https://w3c.github.io/resource-hints/#fetching-the-resource-hint-link needs updating.

`hint.as = "html";` should be `hint.as = "document";` as defined in [[PRELOAD]](https://w3c.github.io/preload/#as-attribute).

### PR DESCRIPTION
**Pull request by marcoscaceres**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/resource-hints/pull/80.html" title="Last updated on Apr 30, 2018, 2:21 AM GMT (b053f4e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/resource-hints/80/7efd7c4...b053f4e.html" title="Last updated on Apr 30, 2018, 2:21 AM GMT (b053f4e)">Diff</a>

### CODE REVIEW

**Comment by yoavweiss** [comment]
Thanks for catching that! :) I wonder if we should replace those values or remove `as` altogether. (although https://github.com/w3c/resource-hints/issues/78 raises a use-case for it)

**Review by yoavweiss — APPROVED** [review]
LGTM

**Comment by yoavweiss** [comment]
Probably easiest to merge this change and see in the future regarding `as` removal.

**Comment by igrigorik** [comment]
> Probably easiest to merge this change and see in the future regarding as removal.

+1. I thought we did already.. Is there a use case for `as` on prefetch? If not, let's remove it to reduce confusion.

**Pull request merged**
