### PR TITLE
crossorigin attribute use with preconnect/prefetch

### PR DESCRIPTION
**Pull request by igrigorik**
For context, see: https://github.com/w3c/resource-hints/issues/32

### CODE REVIEW

**Comment by yoavweiss** [comment]
LGTM

**Comment by annevk** [comment]
Seems reasonable. Though you might want to be more explicit in pointing out the implications.

**Comment by igrigorik** [comment]
Note: blocked on feedback in https://codereview.chromium.org/1131293004/. 

Specifically, there is an open question on whether we need this at all for preconnect in particular (prefetch needs it regardless). It seems that we've conflated "anonymous request" with "linkability through socket reuse", but as Ryan pointed out, that may be unnecessary. 

Next steps: Ryan & myself to draft a summary doc. Once we have clarity on above we can decide on how to proceed.

**Comment by igrigorik** [comment]
Resolution to previous discussion around preconnect + crossorigin: https://codereview.chromium.org/1131293004/#msg43

**Pull request merged**
