### PR TITLE
adopting @mnot's suggested change

### PR DESCRIPTION
**Pull request by dret**

### CODE REVIEW

**Comment by dret** [comment]
proposed in http://mailarchive.ietf.org/arch/msg/link-relations/UwV1fEv-GosLw4Uf8OHILaTyppk

**Comment by igrigorik** [comment]
The substantive change here is dropping the explicit mention of "HTML" - correct? For consistency, I'd prefer to keep the wording consistent with other definitions in the doc. 

``` html
<p>The <code><dfn>prerender</dfn></code> link relation type is used to declare a resource that might be required by the next navigation, and that the user agent SHOULD fetch and execute, such that the user agent can deliver a faster response once the resource is requested in the future.
```

Does that work?

**Comment by dret** [comment]
On 2016-02-01 08:36, Ilya Grigorik wrote:

> The substantive change here is dropping the explicit mention of "HTML" -
> correct?

yes. https://tools.ietf.org/html/rfc5988#section-4.1 says:

"Registered relation types MUST NOT constrain the media type of the 
context IRI, and MUST NOT constrain the available representation media 
types of the target IRI.  However, they can specify the behaviours and 
properties of the target resource (e.g., allowable HTTP methods, request 
and response media types that must be supported)."

so the goal is to define the link relation type in a way that does not 
constrain it to a specific media type.

> For consistency, I'd prefer to keep the wording consistent with
> other definitions in the doc.
> <p>The <code><dfn>prerender</dfn></code> link relation type is used to declare a resource that might be required by the next navigation, and that the user agent SHOULD fetch and execute, such that the user agent can deliver a faster response once the resource is requested in the future.
> Does that work?

yes, please see https://github.com/w3c/resource-hints/pull/54 for the 
latest proposal:
- dropped "SHOULD" to "should" in the IANA registration.
- s/declare/identify/ for more link-oriented terminology.

**Comment by igrigorik** [comment]
:+1:

**Comment by dret** [comment]
thanks!

**Comment by dret** [comment]
asking on the list about these changes: http://mailarchive.ietf.org/arch/msg/link-relations/Nyz3f1H0apy_RH7JmevTmX51ihg

**Pull request merged**
